### ISSUE TITLE
EmailMessage AR undefined field.

### ISSUE THREAD

**Issue by Ragazzo** [digiaonline/yii-emailer#2]
When sending email got that error: `Property "EmailMessage.sentTime" is not defined.`. So should this property must be added as `public` or maybe it is some error and it must be `created` AR attribute?

problem is here in `send()` method

``` php
$model->sentTime = date('Y-m-d H:i:s');
```

P.S. for now, for myself i simple added 

``` php
public $sentTime;
```

to EmailMessage AR, but i think that this must be added to the table, because of needed info. also must be `sent_time` i think.

**Comment by cniska** [comment]
This was already fixed, closing the issue.
