### ISSUE TITLE
Pass data to view issue

### ISSUE THREAD

**Issue by Ragazzo** [digiaonline/yii-emailer#3]
Cant pass in current implementation objects/arrays (any differs from string) to view through the `$data` array in method `createMessage`, because of this error:
`Object of class ... could not be converted to string`. It occurs at this line:
https://github.com/nordsoftware/yii-emailer/blob/master/components/Emailer.php#L136
So i think this replacement can be removed because of it is only needed for pageTitle and looks like strange feature.

**Comment by cniska** [comment]
This has now been fixed. I remove the find and replace for the subject attribute.
