### ISSUE TITLE
Undefined t() function

### ISSUE THREAD

**Issue by Borales** [digiaonline/yii-emailer#5]
https://github.com/nordsoftware/yii-emailer/blob/master/controllers/EmailController.php#L38
I'm not sure, but seem to be a typo here, must be Yii::t()
Am I right?

**Comment by cniska** [comment]
Aye, that is correct. We use a shortcut function t() in our projects so it must have slipped into the emailer module by mistake. I'll fix it right away.

**Comment by Borales** [comment]
@Crisu83 thanks!
