### ISSUE TITLE
require stable versions in composer.json

### ISSUE THREAD

**Issue by schmunk42** [digiaonline/yii-emailer#6]
These two are only available with stability dev in your root package, would be nice if you could create at least a 0.1 tag for them.

```
"nordsoftware/yii-utils": "dev-master",
"crisu83/yii-formatter": "dev-master"
```

**Comment by cniska** [comment]
There is tags for this repo now, just added them this morning.

**Comment by schmunk42** [comment]
I meant not for this repo, but for yii-utils and yii-formatter. Composer does not see them if you're in a stable project. 
Unless you specify a dev-version for the deps.

**Comment by schmunk42** [comment]
Could you reopen this or won't you fix it?

Current code:

```
"require": {
    "nordsoftware/yii-utils": "dev-master",
    "swiftmailer/swiftmailer": "4.3.0",
    "crisu83/yii-formatter": "dev-master"
},
```

**Comment by hugovk** [comment]
Closing and archiving repo.
